"""initial models

Revision ID: 7dc168f10aac
Revises: 
Create Date: 2026-07-20 16:58:24.263244

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7dc168f10aac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###